# Generated by Django 4.1.2 on 2022-11-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка авто')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
            },
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет авто')),
            ],
            options={
                'verbose_name': 'Цвет авто',
                'verbose_name_plural': 'Цвета авто',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_of_car', models.CharField(max_length=50, verbose_name='Модель авто')),
                ('brand_of_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='CarOrder.carbrand', verbose_name='Марка авто')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата заказа')),
                ('count', models.IntegerField(verbose_name='Количество авто')),
                ('car_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='CarOrder.carcolor', verbose_name='Цвет авто')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='CarOrder.carmodel', verbose_name='Модель авто')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date'],
            },
        ),
    ]
